### ISSUE TITLE
Immersive engineering entities are invisible.

### ISSUE THREAD

**Issue by runelee2** [waddon1/Technical-Electrical-Final-Frontiers#3]
Wires not showing up is not entirely unexpected, but my windmill also didn't render. it seems anything that can be in a dynamic position I can't see. The wires still work(I take damage from the LVs, and they hook up to connectors/relays and power machinery fine.), but they are invisible.

**Comment by runelee2** [comment]
Realized I should probably try turning off my shader and texture pack. fixed the windmill. Not sure about the wires but it seems to be a common enough issues with LVs I'd need to do more testing.

**Comment by runelee2** [comment]
Further conclusions:
- All the shader packs were causing the windmill to disappear.(Not unexpected)
- Texturepacks were fine in testing during singleplayer and multiplayer.

**Comment by waddon1** [comment]
This is fixed in next TE update 3.2.2

**Comment by waddon1** [comment]
Update is out now
