### ISSUE TITLE
Providing two mrpack files is an invalid use case

### ISSUE THREAD

**Issue by itzg** [waddon1/Technical-Electrical-Final-Frontiers#4]
[According to the Modrinth team (in their Discord)](https://discord.com/channels/734077874708938864/1103139849852162158/1172996553821126757) publishing two mrpack files on https://modrinth.com/modpack/technical-electrical/version/viPgd7Mi is an invalid use case. You're welcome to immediately close this issue, but wanted to make you aware since one of my users requested that the non-primary, server file be selected from the version.

**Comment by waddon1** [comment]
Hi, I had some issues a while ago with the mrpack server system and I had to make 2 seperate files. Those issues have since been fixed, so I will try and get this solved in the next update

**Comment by itzg** [comment]
Thanks!

**Comment by waddon1** [comment]
Fixed with 3.4.1
