### ISSUE TITLE
Installing v3.5.3 on Modrinth fails with an Invalid Version error

### ISSUE THREAD

**Issue by snewell92** [waddon1/Technical-Electrical-Final-Frontiers#6]
When I try to install the latest neoforge version of Technical Electrical on Modrinth, I get an error. This is only on the latest, v3.5.4. I am able to install v3.5.3 :+1:

![image](https://github.com/waddon1/Technical-Electrical/assets/25957964/13b3febb-b672-47c8-a830-c3ad2615ffe7)

**Comment by waddon1** [comment]
It's a Modrinth issue as they haven't added the latest version of NeoForge. Try using the Forge version instead.
