### ISSUE TITLE
[Suggestion] Add CC: Tweaked 

### ISSUE THREAD

**Issue by aaaaaaaaargh** [waddon1/Technical-Electrical-Final-Frontiers#7]
I think [CC: Tweaked](https://tweaked.cc/) would be a perfect addition to this modpack. I tested the latest versions of both the mod and Technical Electrical and didn't experience any issues whatsoever. 

I prepared the required .pw.toml file by looking at the other configs in the repository. I rather would've created a PR but since both branches seem to be pretty outdated I wasn't so sure about where to do that.

[cc-tweaked.pw.toml](https://github.com/waddon1/Technical-Electrical/files/13999692/cc-tweaked.pw.toml.txt)

Would you consider this as an addition for the next release?

**Comment by waddon1** [comment]
I'm gonna update all the branches soon, I'll take a look at this in the next few days too.

**Comment by waddon1** [comment]
Added in 3.6.1
